[project]
name = "road-damage-classification"
version = "0.1.0"
description = "road damage detection with false positive reduction"
readme = "README.md"
requires-python = ">=3.12, <3.13" 
dependencies = [
    "albumentations",
    "jupyter",
    "matplotlib",
    "numpy",
    "opencv-python",
    "pandas",
    "scikit-learn",
    "seaborn",
    "torch",
    "torchvision",
    "ultralytics",
    "wandb",
    "kaggle",
    "python-dotenv",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = [
    { index = "pytorch-cu121", marker = "sys_platform == 'win32'" }, 
    { index = "pytorch-cu121", marker = "sys_platform == 'linux'" }  
]
torchvision = [
    { index = "pytorch-cu121", marker = "sys_platform == 'win32'" },
    { index = "pytorch-cu121", marker = "sys_platform == 'linux'" }
]